version: '3.1'

services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'carteira'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'